2024資訊安全測驗

<!DOCTYPE html>
<html lang="zh-Hant">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>東捷資訊服務股份有限公司 資訊安全測驗</title>
    <style>
        body {
            font-family: Arial, sans-serif;
        }
        .quiz-container {
            width: 50%;
            margin: auto;
            border: 1px solid #ccc;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 2px 2px 10px rgba(0, 0, 0, 0.1);
        }
        .question {
            margin-bottom: 20px;
        }
        .options {
            list-style-type: none;
            padding: 0;
        }
        .options li {
            margin-bottom: 10px;
        }
        .result {
            margin-top: 20px;
            font-size: 1.2em;
            font-weight: bold;
        }
        .input-group {
            margin-bottom: 20px;
        }
        .input-group label {
            display: block;
            margin-bottom: 5px;
        }
        .input-group input {
            width: 100%;
            padding: 8px;
            box-sizing: border-box;
        }
    </style>
</head>
<body>

<div class="quiz-container">
    <h1>資訊安全測驗</h1>
    <div class="input-group">
        <label for="department">部門：</label>
        <input type="text" id="department" name="department" required>
    </div>
    <div class="input-group">
        <label for="name">姓名：</label>
        <input type="text" id="name" name="name" required>
    </div>
    <div id="quiz">
        <!-- 問題和選項將會動態插入這裡 -->
    </div>
    <button onclick="submitQuiz()">提交測驗</button>
    <div id="result" class="result"></div>
</div>

<script>
    const quizData = [
        {
            question: "以下哪一項是強密碼的特徵？",
            options: ["僅包含小寫字母", "僅包含數字", "包含大寫字母、小寫字母和符號", "包含生日日期"],
            correct: 2
        },
        {
            question: "在公共 Wi-Fi 上哪一項是安全的做法？",
            options: ["訪問網銀網站", "進行網上購物", "使用 VPN", "分享個人資料"],
            correct: 2
        },
        {
            question: "什麼是網路釣魚？",
            options: ["一種網絡釣魚活動", "發送垃圾郵件的行為", "嘗試獲取敏感信息的欺詐行為", "在網上購物"],
            correct: 2
        },
        {
            question: "在公共 Wi-Fi 上哪一項是安全的做法？",
            options: ["訪問網銀網站", "進行網上購物", "使用 VPN", "分享個人資料"],
            correct: 2
        },
        {
            question: "什麼是網路釣魚？",
            options: ["一種網絡釣魚活動", "發送垃圾郵件的行為", "嘗試獲取敏感信息的欺詐行為", "在網上購物"],
            correct: 2
        },
        {
            question: "什麼是網路釣魚？",
            options: ["一種網絡釣魚活動", "發送垃圾郵件的行為", "嘗試獲取敏感信息的欺詐行為", "在網上購物"],
            correct: 2
        },
    ];

    function loadQuiz() {
        const quizContainer = document.getElementById('quiz');
        quizContainer.innerHTML = '';
        quizData.forEach((q, index) => {
            const questionElem = document.createElement('div');
            questionElem.classList.add('question');
            questionElem.innerHTML = `
                <h3>${index + 1}. ${q.question}</h3>
                <ul class="options">
                    ${q.options.map((option, i) => `
                        <li>
                            <label>
                                <input type="radio" name="question${index}" value="${i}"> ${option}
                            </label>
                        </li>
                    `).join('')}
                </ul>
            `;
            quizContainer.appendChild(questionElem);
        });
    }

    async function submitQuiz() {
        const department = document.getElementById('department').value;
        const name = document.getElementById('name').value;

        if (!department || !name) {
            alert('請輸入部門和姓名');
            return;
        }

        let score = 0;
        quizData.forEach((q, index) => {
            const selectedOption = document.querySelector(`input[name="question${index}"]:checked`);
            if (selectedOption && parseInt(selectedOption.value) === q.correct) {
                score++;
            }
        });

        document.getElementById('result').innerText = `你的得分是：${score} / ${quizData.length}`;

        const response = await fetch("https://script.google.com/macros/s/AKfycbw8gaPYdI3xQkHdCT-PMZMQnGgR5hida_Mjxf-3hZx1/dev", {
            method: "POST",
            headers: {
                "Content-Type": "application/json"
            },
            body: JSON.stringify({
                department: department,
                name: name,
                score: score
            })
        });

        if (response.ok) {
            console.log("分數已保存！");
        } else {
            console.error("錯誤：無法保存分數", await response.text());
        }
    }

    window.onload = loadQuiz;
</script>

</body>
</html>
